In [330]:
import pandas as pd
import seaborn as sns
import numpy as np

1. Create a Series of 5 student names.

In [331]:
s=pd.Series(['Harshith Reddy','Vikram','Aditya','Viraj','Priyanshu'])
s

0    Harshith Reddy
1            Vikram
2            Aditya
3             Viraj
4         Priyanshu
dtype: object

2. Create a Series of 5 marks and display it.

In [332]:
s2=pd.Series([78,63,57,80,92],name='Marks')
s2

0    78
1    63
2    57
3    80
4    92
Name: Marks, dtype: int64

3. Create a Series with custom index labels like A, B, C, D.

In [333]:
s.index=['A','B','C','D','E']
s

A    Harshith Reddy
B            Vikram
C            Aditya
D             Viraj
E         Priyanshu
dtype: object

4. Access the third value from a Series.

In [334]:
s.iloc[2]

'Aditya'

5. Access a value from a Series using its custom label.

In [335]:
s.loc['E']

'Priyanshu'

6. Change one value in a Series.

In [336]:
s['A']='Harshith'
s

A     Harshith
B       Vikram
C       Aditya
D        Viraj
E    Priyanshu
dtype: object

7. Add 10 to every value in a numeric Series.

In [337]:
s2+10

0     88
1     73
2     67
3     90
4    102
Name: Marks, dtype: int64

8. Find the maximum value in a Series.

In [338]:
s2.max()

92

9. Find the minimum value in a Series.

In [339]:
s2.min()

57

10. Find the mean of a numeric Series.

In [340]:
s2.mean()

74.0

11. Filter only values greater than 50 in a Series.

In [341]:
s2[s2>50]

0    78
1    63
2    57
3    80
4    92
Name: Marks, dtype: int64

12. Create a Series from a dictionary.

In [342]:
data={
    'Harshith':92,
    'Viraj':87,
    'Aashi':91,
    'Aditya':78,
    'Vikram':82,
    'Priyanshu':85,
    'Nitin': np.nan
    }
s3=pd.Series(data)
s3

Harshith     92.0
Viraj        87.0
Aashi        91.0
Aditya       78.0
Vikram       82.0
Priyanshu    85.0
Nitin         NaN
dtype: float64

13. Check the index of a Series.

In [343]:
s3.index

Index(['Harshith', 'Viraj', 'Aashi', 'Aditya', 'Vikram', 'Priyanshu', 'Nitin'], dtype='object')

14. Check the values of a Series.

In [344]:
s3.values

array([92., 87., 91., 78., 82., 85., nan])

15. Convert a Series into a list.

In [345]:
s3.to_list() #list(s3)

[92.0, 87.0, 91.0, 78.0, 82.0, 85.0, nan]

16. Check which values in a Series are null.

In [346]:
s3.isna()

Harshith     False
Viraj        False
Aashi        False
Aditya       False
Vikram       False
Priyanshu    False
Nitin         True
dtype: bool

17. Fill missing values in a Series with 0.

In [347]:
s3.fillna(89,inplace=True)
s3

Harshith     92.0
Viraj        87.0
Aashi        91.0
Aditya       78.0
Vikram       82.0
Priyanshu    85.0
Nitin        89.0
dtype: float64

18. Count how many times each value appears in a Series.

In [348]:
s3.value_counts()

92.0    1
87.0    1
91.0    1
78.0    1
82.0    1
85.0    1
89.0    1
Name: count, dtype: int64

19. Sort a Series by values.

In [349]:
s3.sort_values()

Aditya       78.0
Vikram       82.0
Priyanshu    85.0
Viraj        87.0
Nitin        89.0
Aashi        91.0
Harshith     92.0
dtype: float64

20. Sort a Series by index.

In [350]:
s3.sort_index()

Aashi        91.0
Aditya       78.0
Harshith     92.0
Nitin        89.0
Priyanshu    85.0
Vikram       82.0
Viraj        87.0
dtype: float64

21. Create a DataFrame of 5 students with columns Name, Age, Marks.

In [351]:
data={
    'Name':['Harshith', 'Viraj', 'Aditya', 'Vikram', 'Priyanshu','Aashi','Abhishek','Nitin'],
    'Age':[21,21,23,23,23,23,25,21],
    'Marks':[92, 87, 91, 78, 82, 85,79,89]
}
df=pd.DataFrame(data)
df

        Name  Age  Marks
0   Harshith   21     92
1      Viraj   21     87
2     Aditya   23     91
3     Vikram   23     78
4  Priyanshu   23     82
5      Aashi   23     85
6   Abhishek   25     79
7      Nitin   21     89

22. Display the first 3 rows of a DataFrame.

In [352]:
df.iloc[:3]

       Name  Age  Marks
0  Harshith   21     92
1     Viraj   21     87
2    Aditya   23     91

23. Display the last 2 rows of a DataFrame.

In [353]:
df.iloc[-2:]

       Name  Age  Marks
6  Abhishek   25     79
7     Nitin   21     89

24. Display only one column from a DataFrame.

In [354]:
df.Marks

0    92
1    87
2    91
3    78
4    82
5    85
6    79
7    89
Name: Marks, dtype: int64

25. Display two columns from a DataFrame.

In [355]:
df[['Name','Age']]

        Name  Age
0   Harshith   21
1      Viraj   21
2     Aditya   23
3     Vikram   23
4  Priyanshu   23
5      Aashi   23
6   Abhishek   25
7      Nitin   21

26. Add a new column called Passed based on Marks > 40.

In [356]:
df['P/F']=df['Marks'].apply(lambda x: 'Pass' if x>40 else 'Fail')
df

        Name  Age  Marks   P/F
0   Harshith   21     92  Pass
1      Viraj   21     87  Pass
2     Aditya   23     91  Pass
3     Vikram   23     78  Pass
4  Priyanshu   23     82  Pass
5      Aashi   23     85  Pass
6   Abhishek   25     79  Pass
7      Nitin   21     89  Pass

27. Add a new column called Bonus with fixed value 5.

In [357]:
df['Bonus']=5
df

        Name  Age  Marks   P/F  Bonus
0   Harshith   21     92  Pass      5
1      Viraj   21     87  Pass      5
2     Aditya   23     91  Pass      5
3     Vikram   23     78  Pass      5
4  Priyanshu   23     82  Pass      5
5      Aashi   23     85  Pass      5
6   Abhishek   25     79  Pass      5
7      Nitin   21     89  Pass      5

28. Change the values of one existing column.

In [358]:
df['Bonus']=2
df

        Name  Age  Marks   P/F  Bonus
0   Harshith   21     92  Pass      2
1      Viraj   21     87  Pass      2
2     Aditya   23     91  Pass      2
3     Vikram   23     78  Pass      2
4  Priyanshu   23     82  Pass      2
5      Aashi   23     85  Pass      2
6   Abhishek   25     79  Pass      2
7      Nitin   21     89  Pass      2

29. Delete one column from a DataFrame.

In [359]:
df.drop(columns='Bonus')

        Name  Age  Marks   P/F
0   Harshith   21     92  Pass
1      Viraj   21     87  Pass
2     Aditya   23     91  Pass
3     Vikram   23     78  Pass
4  Priyanshu   23     82  Pass
5      Aashi   23     85  Pass
6   Abhishek   25     79  Pass
7      Nitin   21     89  Pass

30. Rename a column in a DataFrame.

In [360]:
df.rename(columns={'Bonus':'Extra Marks'})

        Name  Age  Marks   P/F  Extra Marks
0   Harshith   21     92  Pass            2
1      Viraj   21     87  Pass            2
2     Aditya   23     91  Pass            2
3     Vikram   23     78  Pass            2
4  Priyanshu   23     82  Pass            2
5      Aashi   23     85  Pass            2
6   Abhishek   25     79  Pass            2
7      Nitin   21     89  Pass            2

31. Set Name as index of the DataFrame.

In [361]:
df.set_index('Name',inplace=True)
df

           Age  Marks   P/F  Bonus
Name
Harshith    21     92  Pass      2
Viraj       21     87  Pass      2
Aditya      23     91  Pass      2
Vikram      23     78  Pass      2
Priyanshu   23     82  Pass      2
Aashi       23     85  Pass      2
Abhishek    25     79  Pass      2
Nitin       21     89  Pass      2

32. Reset the index back to default integers.

In [362]:
df.reset_index(inplace=True)
df

        Name  Age  Marks   P/F  Bonus
0   Harshith   21     92  Pass      2
1      Viraj   21     87  Pass      2
2     Aditya   23     91  Pass      2
3     Vikram   23     78  Pass      2
4  Priyanshu   23     82  Pass      2
5      Aashi   23     85  Pass      2
6   Abhishek   25     79  Pass      2
7      Nitin   21     89  Pass      2

33. Select the first row using iloc.

In [363]:
df.iloc[0]

Name     Harshith
Age            21
Marks          92
P/F          Pass
Bonus           2
Name: 0, dtype: object

34. Select a row using loc with label index.

In [364]:
df.loc[6]

Name     Abhishek
Age            25
Marks          79
P/F          Pass
Bonus           2
Name: 6, dtype: object

35. Filter students with Marks greater than 60.

In [365]:
df[df['Marks']>60]

        Name  Age  Marks   P/F  Bonus
0   Harshith   21     92  Pass      2
1      Viraj   21     87  Pass      2
2     Aditya   23     91  Pass      2
3     Vikram   23     78  Pass      2
4  Priyanshu   23     82  Pass      2
5      Aashi   23     85  Pass      2
6   Abhishek   25     79  Pass      2
7      Nitin   21     89  Pass      2

36. Filter students whose Age is less than 20.

In [366]:
df[df['Marks']<20]

Empty DataFrame
Columns: [Name, Age, Marks, P/F, Bonus]
Index: []

37. Find the average Marks of all students.

In [367]:
df.Marks.mean()

85.375

38. Find the student with highest Marks.

In [368]:
df[df['Marks']==df['Marks'].max()]

       Name  Age  Marks   P/F  Bonus
0  Harshith   21     92  Pass      2

39. Sort the DataFrame by Marks in ascending order.

In [369]:
df.sort_values(by='Marks')

        Name  Age  Marks   P/F  Bonus
3     Vikram   23     78  Pass      2
6   Abhishek   25     79  Pass      2
4  Priyanshu   23     82  Pass      2
5      Aashi   23     85  Pass      2
1      Viraj   21     87  Pass      2
7      Nitin   21     89  Pass      2
2     Aditya   23     91  Pass      2
0   Harshith   21     92  Pass      2

40. Sort the DataFrame by Age in descending order.

In [370]:
df.sort_values(by='Marks',ascending=False)

        Name  Age  Marks   P/F  Bonus
0   Harshith   21     92  Pass      2
2     Aditya   23     91  Pass      2
7      Nitin   21     89  Pass      2
1      Viraj   21     87  Pass      2
5      Aashi   23     85  Pass      2
4  Priyanshu   23     82  Pass      2
6   Abhishek   25     79  Pass      2
3     Vikram   23     78  Pass      2

41. Check DataFrame shape.

In [371]:
df.shape

(8, 5)

42. Check DataFrame column names.

In [372]:
df.columns

Index(['Name', 'Age', 'Marks', 'P/F', 'Bonus'], dtype='object')

43. Check DataFrame data types.

In [373]:
df.dtypes

Name     object
Age       int64
Marks     int64
P/F      object
Bonus     int64
dtype: object

44. Check if any values are missing in the DataFrame.

In [374]:
df.isna()

    Name    Age  Marks    P/F  Bonus
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

45. Fill missing values in Marks with the column mean.

In [ ]:

df.loc[len(df)] = ['Harsha', 22, np.nan, 'Pass', 2]
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df

46. Drop rows containing missing values.

In [378]:
df.dropna()

        Name  Age   Marks   P/F  Bonus
0   Harshith   21  92.000  Pass      2
1      Viraj   21  87.000  Pass      2
2     Aditya   23  91.000  Pass      2
3     Vikram   23  78.000  Pass      2
4  Priyanshu   23  82.000  Pass      2
5      Aashi   23  85.000  Pass      2
6   Abhishek   25  79.000  Pass      2
7      Nitin   21  89.000  Pass      2
8     Harsha   22  85.375  Pass      2

47. Count unique values in a column.

In [380]:
df['Age'].nunique()

4

48. Find value counts of a categorical column like Department.

In [381]:
df['Age'].value_counts()

Age
23    4
21    3
22    2
25    1
Name: count, dtype: int64

49. Create a second DataFrame and concatenate it with the first one.

In [384]:
df2=pd.DataFrame([['Vivek','26','62','Pass',2]],columns=df.columns)
pd.concat([df,df2],ignore_index=True)

         Name Age   Marks   P/F  Bonus
0    Harshith  21    92.0  Pass      2
1       Viraj  21    87.0  Pass      2
2      Aditya  23    91.0  Pass      2
3      Vikram  23    78.0  Pass      2
4   Priyanshu  23    82.0  Pass      2
5       Aashi  23    85.0  Pass      2
6    Abhishek  25    79.0  Pass      2
7       Nitin  21    89.0  Pass      2
8      Harsha  22  85.375  Pass      2
9      Harsha  22     NaN  Pass      2
10      Vivek  26      62  Pass      2

50. Create two DataFrames with a common column and merge them.

In [392]:
df2=pd.DataFrame({'Name':['Sanjay','Namitha'],'Dep':['Mining','Micro-Bio']})
df.merge(df2,how='outer')

         Name   Age   Marks   P/F  Bonus        Dep
0       Aashi  23.0  85.000  Pass    2.0        NaN
1    Abhishek  25.0  79.000  Pass    2.0        NaN
2      Aditya  23.0  91.000  Pass    2.0        NaN
3      Harsha  22.0  85.375  Pass    2.0        NaN
4      Harsha  22.0     NaN  Pass    2.0        NaN
5    Harshith  21.0  92.000  Pass    2.0        NaN
6     Namitha   NaN     NaN   NaN    NaN  Micro-Bio
7       Nitin  21.0  89.000  Pass    2.0        NaN
8   Priyanshu  23.0  82.000  Pass    2.0        NaN
9      Sanjay   NaN     NaN   NaN    NaN     Mining
10     Vikram  23.0  78.000  Pass    2.0        NaN
11      Viraj  21.0  87.000  Pass    2.0        NaN