In [1]:
import pandas as pd
import numpy as np

In [3]:
data=[[120,80,7],[150,92,14],[116,88,12]]
pd.DataFrame(data,columns=['IQ','MARKS','LPA'])

    IQ  MARKS  LPA
0  120     80    7
1  150     92   14
2  116     88   12

In [ ]:
data2={
    'iq':[100,116,120,150,103],
       'marks':[80,72,85,90,65],
       'package':[4,6,8,24,7]
       }
data2=pd.DataFrame(data2)
data2

    iq  marks  package
0  100     80        4
1  116     72        6
2  120     85        8
3  150     90       24
4  103     65        7

In [17]:
df=pd.read_csv(r"C:\Users\PGCP-AI\Downloads\movies.csv")
df2=pd.read_csv(r"C:\Users\PGCP-AI\Downloads\ipl-matches.csv")
df.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [16]:
df2.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [9]:
df2.shape

(950, 20)

In [10]:
df.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [11]:
df2.index

RangeIndex(start=0, stop=950, step=1)

In [12]:
df.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [15]:
df.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

In [18]:
df2.sample(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
556,598069,Hyderabad,2013-05-19,2013,72,Sunrisers Hyderabad,Kolkata Knight Riders,"Rajiv Gandhi International Stadium, Uppal",Kolkata Knight Riders,bat,N,Sunrisers Hyderabad,Wickets,5.0,NaN,PA Patel,"['PA Patel', 'S Dhawan', 'GH Vihari', 'CL Whit...","['MS Bisla', 'G Gambhir', 'JH Kallis', 'EJG Mo...",Asad Rauf,S Asnani
318,1082646,Delhi,2017-05-14,2017,56,Delhi Daredevils,Royal Challengers Bangalore,Feroz Shah Kotla,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,10.0,NaN,HV Patel,"['SV Samson', 'KK Nair', 'SS Iyer', 'RR Pant',...","['CH Gayle', 'Vishnu Vinod', 'V Kohli', 'TM He...",CK Nandan,C Shamshuddin

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [ ]:
df.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [22]:
df2.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [28]:
df2.isnull().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [29]:
df2.duplicated().sum()

0

In [31]:
data2.sum(axis=1)

0    184
1    194
2    213
3    264
4    175
dtype: int64

In [35]:
print(df2['City'],type(df2['City']))

0       Ahmedabad
1       Ahmedabad
2         Kolkata
3         Kolkata
4          Mumbai
          ...
945       Kolkata
946        Mumbai
947         Delhi
948    Chandigarh
949     Bangalore
Name: City, Length: 950, dtype: object <class 'pandas.core.series.Series'>

In [37]:
print(df2[['City','Venue','Date']],type(df2[['City','Venue','Date']]))

           City                                       Venue        Date
0     Ahmedabad            Narendra Modi Stadium, Ahmedabad  2022-05-29
1     Ahmedabad            Narendra Modi Stadium, Ahmedabad  2022-05-27
2       Kolkata                       Eden Gardens, Kolkata  2022-05-25
3       Kolkata                       Eden Gardens, Kolkata  2022-05-24
4        Mumbai                    Wankhede Stadium, Mumbai  2022-05-22
..          ...                                         ...         ...
945     Kolkata                                Eden Gardens  2008-04-20
946      Mumbai                            Wankhede Stadium  2008-04-20
947       Delhi                            Feroz Shah Kotla  2008-04-19
948  Chandigarh  Punjab Cricket Association Stadium, Mohali  2008-04-19
949   Bangalore                       M Chinnaswamy Stadium  2008-04-18

[950 rows x 3 columns] <class 'pandas.core.frame.DataFrame'>

In [39]:
df2.loc[[0,2,4,945],['City','Venue','Date']]

          City                             Venue        Date
0    Ahmedabad  Narendra Modi Stadium, Ahmedabad  2022-05-29
2      Kolkata             Eden Gardens, Kolkata  2022-05-25
4       Mumbai          Wankhede Stadium, Mumbai  2022-05-22
945    Kolkata                      Eden Gardens  2008-04-20

In [46]:
data2={
    'name':['Harshith','Viraj','vikram','Aditya','Priyanshu'],
    'iq':[100,116,120,150,103],
       'marks':[80,72,85,90,65],
       'package':[4,6,8,24,7]
       }
data2=pd.DataFrame(data2)
data2

        name   iq  marks  package
0   Harshith  100     80        4
1      Viraj  116     72        6
2     vikram  120     85        8
3     Aditya  150     90       24
4  Priyanshu  103     65        7

In [48]:
data2.set_index('name',inplace=True)

In [ ]:
print(type(df.iloc[0]))

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object <class 'pandas.core.series.Series'>

In [52]:
df.iloc[12:16,0:2]

              title_x    imdb_id
12          Hum Chaar  tt9319812
13      Total Dhamaal  tt7639372
14         Sonchiriya  tt8108200
15  Badla (2019 film)  tt8130968

In [53]:
df2.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [67]:
df2[df2['MatchNumber']=='Final'][['WinningTeam','Season']]

               WinningTeam   Season
0           Gujarat Titans     2022
74     Chennai Super Kings     2021
134         Mumbai Indians  2020/21
194         Mumbai Indians     2019
254    Chennai Super Kings     2018
314         Mumbai Indians     2017
373    Sunrisers Hyderabad     2016
433         Mumbai Indians     2015
492  Kolkata Knight Riders     2014
552         Mumbai Indians     2013
628  Kolkata Knight Riders     2012
702    Chennai Super Kings     2011
775    Chennai Super Kings  2009/10
835        Deccan Chargers     2009
892       Rajasthan Royals  2007/08

In [79]:
sum(df2['SuperOver']=='Y')

14

In [82]:
df2[(df2['WinningTeam']=='Chennai Super Kings') & (df2['City']=='Kolkata')].shape[0]

5

In [ ]:
(df2[df2['TossWinner']==df2['WinningTeam']].shape[0]/df2['WinningTeam'].count())*100
#this analysis says that there is only slight 1.6 persent advantage by winning toss

51.69133192389006

In [88]:
df.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [ ]:
df[(df['imdb_rating']>7.5) & (df['genres'].apply(lambda x:'Action' in x))][['title_x','genres']]

                            title_x                   genres
0          Uri: The Surgical Strike         Action|Drama|War
41             Family of Thakurganj             Action|Drama
84                        Mukkabaaz       Action|Drama|Sport
106                           Raazi    Action|Drama|Thriller
110   Parmanu: The Story of Pokhran     Action|Drama|History
112         Bhavesh Joshi Superhero             Action|Drama
169                The Ghazi Attack      Action|Thriller|War
219                Raag Desh (film)     Action|Drama|History
258                   Irudhi Suttru       Action|Drama|Sport
280                       Laal Rang       Action|Crime|Drama
297                     Udta Punjab       Action|Crime|Drama
354                   Dangal (film)   Action|Biography|Drama
362               Bajrangi Bhaijaan      Action|Comedy|Drama
365          Baby (2015 Hindi film)          Action|Thriller
393      Detective Byomkesh Bakshy!  Action|Mystery|Thriller
449               Titli (2014 film)    Action|Drama|Thriller
536                   Haider (film)       Action|Crime|Drama
589                    Vishwaroopam          Action|Thriller
625                     Madras Cafe    Action|Drama|Thriller
668         Paan Singh Tomar (film)   Action|Biography|Crime
693              Gangs of Wasseypur      Action|Comedy|Crime
694     Gangs of Wasseypur – Part 2      Action|Comedy|Crime
982                    Jodhaa Akbar     Action|Drama|History
1039               1971 (2007 film)         Action|Drama|War
1058       Black Friday (2007 film)       Action|Crime|Drama
1188             Omkara (2006 film)       Action|Crime|Drama
1293             Sarkar (2005 film)       Action|Crime|Drama
1294                          Sehar       Action|Crime|Drama
1361                 Lakshya (film)     Action|Drama|Romance
1432                      Gangaajal       Action|Crime|Drama
1495                 Company (film)       Action|Crime|Drama
1554     The Legend of Bhagat Singh   Action|Biography|Drama
1607        Nayak (2001 Hindi film)    Action|Drama|Thriller

0        True
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627     True
1628    False
Name: genres, Length: 1629, dtype: bool