In [1]:
from sklearn.linear_model import LinearRegression,ElasticNet,Ridge,Lasso
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.metrics import r2_score,root_mean_squared_error
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.impute import SimpleImputer

In [2]:
chemicals=pd.read_csv(r'E:\DataAnalytics\Datasets\ChemicalProcess.csv')
chemicals.head()

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3,7.2,NaN,NaN,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2,7.3,0.0,0.00,11.0,1.1,1.7,2.1

In [3]:
chemicals.isnull().sum().sum()

np.int64(106)

In [4]:
X=chemicals.drop('Yield',axis=1)
y=chemicals['Yield']

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)
X_train.isnull().sum().sum()

np.int64(93)

In [6]:
X_test.isnull().sum().sum()

np.int64(13)

In [7]:

imputer=SimpleImputer(strategy='mean').set_output(transform='pandas')
X_train_imp=imputer.fit_transform(X_train)
X_test_imp=imputer.transform(X_test)
X_train_imp.isnull().sum().sum()

np.int64(0)

In [8]:
X_test_imp.isnull().sum().sum()

np.int64(0)

In [9]:
#Liner Regression
model=LinearRegression()
model.fit(X_train_imp,y_train)

LinearRegression()

In [10]:
y_pred=model.predict(X_test_imp)

In [11]:
print('R 2 score:->',r2_score(y_test,y_pred))
print('Root_Mean:->',root_mean_squared_error(y_test,y_pred))

R 2 score:-> -7.299578219035819
Root_Mean:-> 4.871093773818226

In [12]:
# Ridge
import numpy as np
alpha=np.linspace(0.001,10,20)
scores=[]
for x in alpha:
    model=Ridge(alpha=x)
    model.fit(X_train_imp,y_train)
    y_pred=model.predict(X_test_imp)
    scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
ridgeScr=pd.DataFrame(scores,columns=['Alpha','r2_Score','RMSE_Score']).sort_values('r2_Score',ascending=False)
ridgeScr.head()

      Alpha  r2_Score  RMSE_Score
4  2.106053 -2.459765    3.145008
5  2.632316 -2.466741    3.148177
3  1.579789 -2.469279    3.149329
6  3.158579 -2.483017    3.155559
7  3.684842 -2.504908    3.165460

In [13]:
# lasso
alpha=np.linspace(0.001,10,20)
scores=[]
for x in alpha:
    model=Lasso(alpha=x)
    model.fit(X_train_imp,y_train)
    y_pred=model.predict(X_test_imp)
    scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
lassoScr=pd.DataFrame(scores,columns=['Alpha','r2_Score','RMSE_Score']).sort_values('r2_Score',ascending=False)
lassoScr.head()

C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.011577e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.495603e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.048183e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.662752e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.742686e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.602239e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.415032e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.165782e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.932177e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.921053e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.274440e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.920271e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.810719e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.912961e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.203702e+00, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.854816e-01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

       Alpha  r2_Score  RMSE_Score
15  7.894947  0.325685    1.388449
14  7.368684  0.310737    1.403754
16  8.421211  0.297462    1.417207
17  8.947474  0.274142    1.440536
18  9.473737  0.261814    1.452718

In [14]:
# ElasticNet
alpha=np.linspace(0.001,10,20)
l1_ratio=np.linspace(0.001,1,20)
scores=[]
for x in alpha:
    for y in l1_ratio:
        model=ElasticNet(alpha=x,l1_ratio=y)
        model.fit(X_train_imp,y_train)
        y_pred=model.predict(X_test_imp)
        scores.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
elastScr=pd.DataFrame(scores,columns=['Alpha','r2_Score','RMSE_Score']).sort_values('r2_Score',ascending=False)
elastScr.head()

C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.933718e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.939665e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.945568e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.951422e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.957222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.962965e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.968646e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.974257e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.979794e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.985247e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.990603e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.995878e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.001079e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.006196e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.011210e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.016134e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.020979e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025879e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030918e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035920e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.076756e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.393597e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.636445e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.847484e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.023928e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.168369e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.239733e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.280905e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.324628e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.362559e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.385758e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.331563e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.278003e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.243077e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.223149e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200217e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.157493e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.112249e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.063594e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.011577e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.634767e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.016834e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.275222e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.394713e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.434697e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.455254e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.353553e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.298428e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.200687e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.095194e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.977643e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.845875e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_coordinate_descent.py:842: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.693736e+01, tolerance: 4.417e-02
  model = cd_fast.enet_coordinate_descent(

        Alpha  r2_Score  RMSE_Score
27   0.527263  0.577195    1.099433
43   1.053526  0.576039    1.100934
260  6.842421  0.544886    1.140667
280  7.368684  0.543918    1.141878
81   2.106053  0.543396    1.142532

In [15]:
pd.concat([ridgeScr.iloc[0,:2],lassoScr.iloc[0,0:2],elastScr.iloc[0,0:2]])

Alpha       2.106053
r2_Score   -2.459765
Alpha       7.894947
r2_Score    0.325685
Alpha       0.527263
r2_Score    0.577195
dtype: float64