In [3]:
from sklearn.linear_model import LinearRegression,ElasticNet,Ridge,Lasso
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.metrics import r2_score,root_mean_squared_error
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [12]:
job=pd.read_csv(r'E:\DataAnalytics\Datasets\JobSalary2.csv',index_col='S_No')
job

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0        NaN        88
4          NaN       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7          NaN       51.0        96
8         77.0       64.0       105

In [13]:
job.isna().sum().sum()

3

# imputing the central tendencies manually

In [14]:
# mean
mu=dict(job.mean().round(2))
job.fillna(mu)

      Computer  Marketing  Engineer
S_No
1        84.00      55.00        75
2        90.00      53.00        70
3        63.00      52.57        88
4        75.33      50.00        77
5        63.00      41.00        89
6        75.00      54.00        85
7        75.33      51.00        96
8        77.00      64.00       105

In [15]:
# median
mu=dict(job.median().round(2))
job.fillna(mu)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0       53.0        88
4         76.0       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7         76.0       51.0        96
8         77.0       64.0       105

# Imputing Using Transformer or SimpleImputer

In [23]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='mean').set_output(transform='pandas')
imputer.fit(job) # just calculates the stats  and will not fill into null places
imputer.statistics_
imputer.transform(job).round(2) # transforms the data set by replacing the nulls

      Computer  Marketing  Engineer
S_No
1        84.00      55.00      75.0
2        90.00      53.00      70.0
3        63.00      52.57      88.0
4        75.33      50.00      77.0
5        63.00      41.00      89.0
6        75.00      54.00      85.0
7        75.33      51.00      96.0
8        77.00      64.00     105.0